// SignInPage - generated by QAgentic.
// /dashboard has a form containing a password field (Password) alongside Username
import { expect } from '@playwright/test';
import { BasePage } from './BasePage';

export class SignInPage extends BasePage {
  readonly path = '/dashboard';

  private get username() {
    return this.page.getByTestId('login-username');
  }

  private get password() {
    return this.page.getByTestId('login-password');
  }

  private get signInField() {
    return this.page.getByTestId('login-submit');
  }

  /** Type into the Username field. */
  async enterUsername(value: string): Promise<void> {
    await this.username.fill(value);
  }

  /** Type into the Password field. */
  async enterPassword(value: string): Promise<void> {
    await this.password.fill(value);
  }

  /** Submit the form on this page. */
  async submitForm(): Promise<void> {
    await this.signInField.click();
  }

  /** Still on this page — what a rejected submission looks like. */
  async expectHere(): Promise<void> {
    await expect(this.page).toHaveTitle('Sign in - Acme Residents');
  }

  /** No longer on this page — what an accepted one looks like. */
  async expectLeft(): Promise<void> {
    await expect(this.page).not.toHaveTitle('Sign in - Acme Residents');
  }

  /** The title this page showed during exploration. */
  async expectTitle(title: string): Promise<void> {
    await expect(this.page).toHaveTitle(title);
  }

  /** Sign in with the credentials in the environment. */
  async signIn(): Promise<void> {
    await this.username.fill(process.env.AIQA_APP_USERNAME ?? '');
    await this.password.fill(process.env.AIQA_APP_PASSWORD ?? '');
    await this.submitForm();
  }

  /** Sign in with a deliberately incorrect password. */
  async signInWithWrongPassword(): Promise<void> {
    await this.username.fill(process.env.AIQA_APP_USERNAME ?? '');
    await this.password.fill((process.env.AIQA_APP_PASSWORD ?? 'x') + '-definitely-wrong');
    await this.submitForm();
  }
}
