// Generated by QAgentic - step definitions.
// Steps call Page Object methods; locators never appear here.
import { Given, When, Then } from '@cucumber/cucumber';
import { SignInPage } from '../pages/SignInPage';

let signInPage!: SignInPage;

Given('I am on the Sign in page', async function () {
  signInPage = new SignInPage(this.page);
  await signInPage.goto();
});

When('I sign in on the Sign in page with valid credentials', async function () {
  signInPage = new SignInPage(this.page);
  await signInPage.signIn();
});

Then('I am taken away from the Sign in page', async function () {
  signInPage = new SignInPage(this.page);
  await signInPage.expectLeft();
});

When('I sign in on the Sign in page with an incorrect password', async function () {
  signInPage = new SignInPage(this.page);
  await signInPage.signInWithWrongPassword();
});

Then('I am still on the Sign in page', async function () {
  signInPage = new SignInPage(this.page);
  await signInPage.expectHere();
});

When('I enter {string} in the Password field on the Sign in page', async function (value1: string) {
  signInPage = new SignInPage(this.page);
  await signInPage.enterPassword(value1);
});

Given('I submit the Sign in form', async function () {
  signInPage = new SignInPage(this.page);
  await signInPage.submitForm();
});

When('I enter {string} in the Username field on the Sign in page', async function (value1: string) {
  signInPage = new SignInPage(this.page);
  await signInPage.enterUsername(value1);
});
