"""Code Generation Agent — plan with the model, render with code.

The naive approach asks a coding model to write whole files. Measured on a
five-scenario run that was 55% of all input tokens, on the most expensive tier,
and most of what it produced was boilerplate the platform already knows: the
import block, the class declaration, the base class, getter visibility, async
signatures, formatting.

So the division is inverted:

* **The model plans.** One call returns compact JSON — which Page Objects, which
  methods, which catalogue locator each method uses, and which Page Object
  method each Gherkin step maps to.
* **Code renders the plan.** `renderer.py` emits the TypeScript, applying the
  repository's house style.

Three wins, not one:

1. **Cost** — no boilerplate in the prompt, no file in the completion, and page
   objects and steps share a single call instead of two.
2. **Correctness** — the renderer can only emit locators from the verified
   catalogue, so a hallucinated selector is impossible by construction rather
   than detected afterwards.
3. **Consistency** — house style is applied by code, so it cannot drift between
   files or between runs.

Feature files are still rendered directly from the approved plan: the Gherkin a
human approved is byte-for-byte the Gherkin that lands.
"""

from __future__ import annotations

import json
import re
from pathlib import PurePosixPath
from typing import Any

from agents.base import AgentContext, BaseAgent, json_block
from agents.code_generation.api_renderer import (
    api_checks_from,
    db_checks_from,
    render_api_tests,
    render_db_checks,
    render_db_helper,
    spec_file_name,
)
from agents.code_generation.renderer import (
    GenerationPlan,
    deterministic_plan,
    enrich_plan,
    pascal,
    plan_from_response,
    render_page_object,
    render_steps,
)
from agents.code_generation.visual_renderer import (
    render_visual_tests,
    visual_checks_from,
)
from agents.code_generation.visual_renderer import (
    spec_file_name as visual_spec_file_name,
)
from packages.aiqa_types.enums import AgentName, ArtifactKind, Capability, ChangeType
from packages.aiqa_types.models import CodeBundle, FileChange, TestPlan
from services.discovery.autopilot import DiscoveredFeature
from services.discovery.codegen import describe as describe_generation
from services.discovery.codegen import generation_plan
from tools.filesystem.fs_tools import make_diff

#: How a file says this platform wrote it, and may rewrite it.
#:
#: Both spellings are accepted forever. The product was renamed from "AI QA
#: Engineer" to "QAgentic", and every file generated before that carries the old
#: header — recognising only the new one would make the platform treat its own
#: output as somebody's hand-written work and quietly stop maintaining it.
_GENERATED_MARKERS = ("generated by QAgentic", "generated by AI QA Engineer")

#: A diff larger than this is summarised in the event and read in full from the
#: editor instead. Event rows are replayed to every client that attaches, so a
#: 200 KB diff there would be paid for repeatedly.
_MAX_EVENT_DIFF_CHARS = 6000

PLAN_SYSTEM = """You plan QA automation. You do NOT write files - a renderer emits the code from your plan.

Given the scenarios, the verified locator catalogue and the repository's existing assets, decide:
  1. which Page Objects are needed, and which methods each should expose
  2. which catalogue locator each method uses
  3. which Page Object method each Gherkin step maps to

Rules:
- Reference locators ONLY by a `name` or `locator` string that appears in the catalogue. Anything else
  is discarded, so inventing one wastes your output.
- A Page Object models ONE route. Use only catalogue entries whose `page` matches the route you set,
  and set `route` to that exact value.
- Reuse an existing Page Object instead of proposing a new one wherever it fits.
- Methods are intent-revealing and business-level: `registerResident`, not `clickButton3`.
- `kind` is "action" (fills/clicks), "assertion" (verifies) or "navigation".
- For assertions set `expect` to a Playwright matcher: toBeVisible, toContainText, toHaveText, toHaveValue.
- Every Gherkin step you were given must appear exactly once in `steps`, unless it is listed as already
  existing in the repository - then put it in `reused_steps` instead.
- Mark `setup: true` on the first Given of a scenario so the renderer instantiates and navigates.

Reply with ONE JSON object and nothing else:
{"pages":[{"class":str,"route":str,"description":str,
           "locators":[{"prop":str,"name":str,"locator":str}],
           "methods":[{"name":str,"kind":str,"params":[str],"locators":[str],"expect":str,"intent":str}]}],
 "steps":[{"text":str,"keyword":str,"page":str,"call":str,"setup":bool}],
 "reused_pages":[str],"reused_steps":[str],"notes":[str]}"""


class CodeGenerationAgent(BaseAgent):
    name = AgentName.CODE_GENERATION
    capability = Capability.CODING
    description = "Plans the automation with one model call; renders the TypeScript deterministically."

    def progress(self, ctx: AgentContext) -> float:
        return 0.6

    async def run(self, ctx: AgentContext) -> None:
        plan = ctx.test_plan
        if plan is None:
            raise ValueError("code generation requires an approved test plan")

        layout = self._layout(ctx)
        changes: list[FileChange] = []

        # 1. Feature files — deterministic render of what the human approved.
        changes.extend(self._feature_changes(ctx, plan, layout))

        # 2. One planning call covering page objects *and* steps.
        generation = await self._plan(ctx, plan)

        # 3. Render.
        changes.extend(self._render_pages(ctx, generation, layout))
        changes.extend(self._render_steps(ctx, generation, plan, layout))

        # 4. Test data for data-driven scenarios (no model needed).
        changes.extend(self._data_changes(ctx, plan, layout))

        # 5. API and database checks. The same acceptance criterion verified one
        #    layer down runs in a fraction of the time and fails for a clearer
        #    reason, so it is generated whenever the plan asked for it and the
        #    endpoint was actually observed.
        changes.extend(self._api_changes(ctx, plan, layout))
        changes.extend(self._db_changes(ctx, plan, layout))

        # 6. Visual regression, for routes settled enough to baseline.
        changes.extend(self._visual_changes(ctx, plan, layout))

        # Attach diffs so review is meaningful.
        for change in changes:
            # Ask whether the file is there before reading it. Reading a path
            # that is *expected* to be absent — most generated files are new —
            # recorded six `fs.read_file → failed` traces in a perfectly
            # healthy run. The event log is what the engineer reads to decide
            # whether to trust the output, and a run that cries wolf about its
            # own successes is not one anybody reads twice.
            # `fs.exists` answers with the boolean in `data`; the call itself
            # succeeds either way, which is the whole point of using it here.
            if not self.tool(ctx, "fs.exists", path=change.path).data:
                change.diff = make_diff(change.path, "", change.content)
                continue
            existing = self.tool(ctx, "fs.read_file", path=change.path)
            if existing.ok and isinstance(existing.data, str):
                change.original_content = existing.data
                change.change_type = ChangeType.MODIFY
            change.diff = make_diff(change.path, change.original_content or "", change.content)

        bundle = CodeBundle(
            run_id=ctx.run_id,
            plan_id=plan.id,
            changes=changes,
            summary=(
                f"{len(changes)} file(s): "
                + ", ".join(sorted({c.kind.value for c in changes}))
                + f"; {plan.scenario_count} scenario(s)"
            ),
        )
        ctx.code_bundle = bundle
        self._warn_if_features_are_inert(ctx, changes)

        # Publish the code itself. A client that only sees "code_generation
        # finished" cannot show the engineer what was written, which is the one
        # thing they most need to review. Diffs are capped: the full file is a
        # click away in the editor, and an event row is not the place for it.
        if ctx.tracker is not None:
            ctx.tracker.emit(
                "files_generated",
                f"{len(changes)} file(s) written",
                agent=self.name,
                data={
                    "files": [
                        {
                            "path": change.path,
                            "kind": str(getattr(change.kind, "value", change.kind)),
                            "language": change.language,
                            "change_type": str(getattr(change.change_type, "value", change.change_type)),
                            "rationale": change.rationale[:200],
                            "lines": change.content.count("\n") + 1,
                            "diff": change.diff[:_MAX_EVENT_DIFF_CHARS],
                            "diff_truncated": len(change.diff) > _MAX_EVENT_DIFF_CHARS,
                            "todos": change.content.count("TODO(aiqa)") + change.content.count("test.fixme"),
                        }
                        for change in changes
                    ]
                },
            )
        ctx.note(
            f"generated {len(changes)} file(s), {bundle.total_bytes} bytes "
            f"({len(generation.pages)} page object(s), {len(generation.steps)} step(s) planned)"
        )
        if generation.reused_pages:
            ctx.note(f"reused existing page object(s): {', '.join(generation.reused_pages)}")
        if ctx.tracker:
            for trace in getattr(ctx.tracker, "agent_traces", []):
                if trace.agent == self.name and not trace.output_summary:
                    trace.output_summary = f"{len(changes)} files rendered from a planned spec"

    # ------------------------------------------------------------------ #
    def _layout(self, ctx: AgentContext) -> dict[str, str]:
        defaults = (ctx.standards.get("layout", {}) or {}).copy()
        learned = (ctx.repo_profile.detected_layout if ctx.repo_profile else {}) or {}
        defaults.update({k: v for k, v in learned.items() if v})
        return {
            "features_dir": defaults.get("features_dir", "tests/features"),
            "steps_dir": defaults.get("steps_dir", "tests/steps"),
            "pages_dir": defaults.get("pages_dir", "tests/pages"),
            "fixtures_dir": defaults.get("fixtures_dir", "tests/fixtures"),
            "utils_dir": defaults.get("utils_dir", "tests/utils"),
            "data_dir": defaults.get("data_dir", "tests/data"),
            "api_dir": defaults.get("api_dir", "tests/api"),
            "visual_dir": defaults.get("visual_dir", "tests/visual"),
            "tests_dir": defaults.get("tests_dir", "tests"),
        }

    def _plan_from_discovery(
        self, ctx: AgentContext, plan: TestPlan, catalog: list[dict[str, Any]]
    ) -> GenerationPlan | None:
        """Page objects and bindings for a plan the crawl already decided."""
        if not ctx.metadata.get("autopilot"):
            return None
        raw = ctx.metadata.get("discovered_features") or []
        features = [DiscoveredFeature(**entry) for entry in raw if isinstance(entry, dict)]
        if not features or not catalog:
            return None

        titles: dict[str, str] = {}
        app_map = ctx.application_map
        for route, page in (getattr(app_map, "pages", {}) or {}).items():
            title = page.get("title") if isinstance(page, dict) else getattr(page, "title", "")
            if title:
                titles[route] = str(title)

        generation = generation_plan(
            features, plan, catalog,
            base_class=self._base_class(ctx),
            page_titles=titles,
        )
        if not generation.pages:
            return None

        bound = {step.text for step in generation.steps}
        planned = {
            step.text for feature in plan.features
            for scenario in feature.scenarios for step in scenario.steps
        }
        unbound = sorted(planned - bound)
        ctx.note(f"generated deterministically: {describe_generation(generation)}")
        if unbound:
            # Named rather than approximated. Binding a step to the nearest
            # thing that compiles is how a suite ends up exercising the wrong
            # control and passing.
            ctx.warn(
                f"{len(unbound)} planned step(s) have no observed element behind them: "
                + "; ".join(f'"{text}"' for text in unbound[:4])
            )
        return generation

    def _base_class(self, ctx: AgentContext) -> str:
        return ((ctx.repo_profile.naming_conventions if ctx.repo_profile else {}) or {}).get(
            "page_object_base_class", ""
        )

    # -- 1. features ---------------------------------------------------- #
    def _feature_changes(self, ctx: AgentContext, plan: TestPlan, layout: dict[str, str]) -> list[FileChange]:
        # A feature whose scenarios were all dropped as duplicates renders to a
        # bare `Feature:` line. Writing that leaves an empty file in the suite
        # that looks like coverage and runs nothing, so it is skipped.
        empty = [f.name for f in plan.features if not f.scenarios]
        if empty:
            ctx.note(
                f"skipped {len(empty)} feature file(s) with no scenarios "
                f"({', '.join(empty[:3])}) — every scenario was already covered"
            )
        return [
            FileChange(
                path=str(PurePosixPath(layout["features_dir"]) / (feature.file_name or "feature.feature")),
                change_type=ChangeType.CREATE,
                kind=ArtifactKind.FEATURE,
                content=feature.to_gherkin(),
                language="gherkin",
                rationale="Rendered from the approved test plan, so the Gherkin matches what was reviewed.",
            )
            for feature in plan.features
            if feature.scenarios
        ]

    # ------------------------------------------------------------------ #
    def _warn_if_features_are_inert(self, ctx: AgentContext, changes: list[FileChange]) -> None:
        """A .feature file nothing runs is a document, not a test.

        `bdd` being true only means a BDD library is in package.json. The demo
        repository had `@cucumber/cucumber` and `playwright-bdd` installed, no
        runner wired to the features directory, and a `playwright test` script
        that matched `*.spec.ts` only -- so every feature and step file the
        platform had ever written sat there compiling cleanly and executing
        never. It took running the suite by hand to notice.
        """
        profile = ctx.repo_profile
        if profile is None or not getattr(profile, "bdd", False):
            return
        if getattr(profile, "bdd_runnable", False):
            return
        features = [c for c in changes if str(getattr(c, "path", "")).endswith(".feature")]
        if not features:
            return
        ctx.warn(
            f"{len(features)} feature file(s) written, but nothing in this repository runs them: "
            "there is no cucumber config and the Playwright config has no defineBddConfig. "
            "They will compile and never execute."
        )

    # -- 2. the single planning call ------------------------------------ #
    async def _plan(self, ctx: AgentContext, plan: TestPlan) -> GenerationPlan:
        catalog = ctx.metadata.get("locator_catalog", []) or []

        # Autopilot wrote the scenarios itself, from a fixed vocabulary, against
        # elements it observed. Both ends of the mapping are therefore known, and
        # asking a model to rediscover it was the last place invention could get
        # in — it duly did: one run planned fifteen good scenarios and blocked
        # twenty of their steps, because the page objects it generated had no
        # `goto`, no way to sign in, and nothing that could say "we are still on
        # this page". The plan was right and none of it ran.
        deterministic = self._plan_from_discovery(ctx, plan, catalog)
        if deterministic is not None:
            return deterministic

        existing_pages = [p.name for p in (ctx.repo_profile.symbols_of("page_object") if ctx.repo_profile else [])]
        existing_steps = [
            s.name for s in (ctx.repo_profile.symbols_of("step") if ctx.repo_profile else [])
        ][:30]

        background = [
            {"keyword": s.keyword, "text": s.text} for feature in plan.features for s in feature.background
        ]
        scenarios = [
            {
                "id": scenario.test_id,
                "name": scenario.name,
                # Background runs before every scenario, so its steps need
                # definitions like any other. They were omitted here, which is
                # why a feature whose Background said "Given I am on the login
                # page" generated no Given at all: Cucumber reported the step
                # undefined and the whole suite failed before its first
                # assertion. It compiled, of course. Compiling was never the
                # question.
                "steps": [
                    {"keyword": s["keyword"], "text": s["text"]} for s in background
                ]
                + [{"keyword": s.keyword, "text": s.text} for s in scenario.steps],
            }
            for feature in plan.features
            for scenario in feature.scenarios
        ]

        # The catalogue is the only application context the model needs. The
        # repository briefing is already distilled into the standards prefix, and
        # nothing else is sent — this is where the token saving comes from.
        compact_catalog = [
            {
                "page": item.get("page"),
                "name": item.get("name"),
                "role": item.get("role"),
                "required": item.get("required"),
                "locator": item.get("locator"),
            }
            for item in catalog[:60]
        ]

        user = "\n".join(
            [
                f"Target Page Objects: {', '.join(plan.page_objects_needed) or '(decide from the scenarios)'}",
                f"Base class to extend: {self._base_class(ctx) or '(none)'}",
                "",
                "## Verified locator catalogue (the ONLY locators you may reference)",
                json_block(compact_catalog, limit=5000)
                if compact_catalog
                else "(empty - the application could not be crawled)",
                "",
                "## Existing Page Objects (reuse where they fit)",
                ", ".join(existing_pages) or "(none)",
                "",
                "## Existing step definitions (do NOT reimplement - list in reused_steps)",
                *([f"  - {s[:110]}" for s in existing_steps] or ["(none)"]),
                "",
                "## Background steps",
                json_block(background, limit=800) if background else "(none)",
                "",
                "## Scenarios to support",
                json_block(scenarios, limit=6000),
                "",
                "Plan the Page Objects and step bindings.",
            ]
        )

        # The house-style prefix is byte-identical across runs, so a provider
        # that supports prompt caching bills it once rather than every call.
        prefix = ctx.metadata.get("standards_prefix", "")
        system = PLAN_SYSTEM + (f"\n\n## House standards\n{prefix}" if prefix else "")

        raw = await self.ask_json(
            ctx, system, user,
            task="code_generation.plan",
            fallback=None,
            # Enough for a multi-page plan with step bindings. Truncation here
            # drops the run to the deterministic scaffold, which is a much
            # worse outcome than a slightly longer call — and 6,000 was not
            # enough for six scenarios, so the common case paid for a truncated
            # call *and* a retry. Output is free on these models; a wasted
            # round trip is the only thing that costs anything.
            max_tokens=10_000,
            cacheable_prefix_chars=len(system),
        )

        generation = plan_from_response(
            raw,
            catalog=catalog,
            base_class=self._base_class(ctx),
            default_route=_guess_route(ctx),
        )

        expected = [pascal(n) for n in plan.page_objects_needed if n]
        if not generation.pages:
            ctx.warn("no usable generation plan from the model; falling back to a deterministic scaffold")
            class_name = expected[0] if expected else _page_class_name(plan.features[0].name)
            generation = deterministic_plan(
                class_name, catalog, scenarios,
                base_class=self._base_class(ctx), route=_guess_route(ctx),
            )
        else:
            # The approved plan already names the Page Objects. A model that
            # invents a different name is corrected rather than obeyed, so a
            # stray prompt echo cannot become a class name in the repository.
            for index, page in enumerate(generation.pages):
                if expected and page.class_name not in expected and index < len(expected):
                    ctx.note(f"renamed planned page object {page.class_name} -> {expected[index]}")
                    page.class_name = expected[index]
                elif not _plausible_class_name(page.class_name):
                    fallback = _page_class_name(plan.features[0].name if plan.features else "Feature")
                    ctx.note(f"implausible page object name {page.class_name} -> {fallback}")
                    page.class_name = fallback

        # Complete anything the plan left mechanical: unbound locators, missing
        # step bindings. Recoverable from the catalogue, so it costs no call.
        generation = enrich_plan(generation, catalog, scenarios, base_class=self._base_class(ctx))
        return generation

    # -- 3a. page objects ------------------------------------------------ #
    def _render_pages(
        self, ctx: AgentContext, generation: GenerationPlan, layout: dict[str, str]
    ) -> list[FileChange]:
        members = _existing_members(ctx)
        existing = set(members)
        changes: list[FileChange] = []
        for page in generation.pages:
            if page.class_name in existing:
                missing = {m.name for m in page.methods} - members[page.class_name]
                path = str(PurePosixPath(layout["pages_dir"]) / f"{page.class_name}.ts")
                if missing and self._is_generated(ctx, path):
                    # Reuse must mean "it already does the job", not "never
                    # touch it". One early run — before exploration worked —
                    # left a `ResidentRegistrationPage` with no locators and a
                    # single method, and every later run dutifully reused it and
                    # produced eight pending steps bound to methods it does not
                    # have. A bad file generated once was poisoning the
                    # repository indefinitely.
                    #
                    # Only files this platform wrote are rewritten; the header
                    # says so. A hand-written Page Object is left alone and its
                    # missing methods surface as TODOs for a human.
                    ctx.note(
                        f"{page.class_name} exists but lacks {', '.join(sorted(missing)[:4])} — "
                        "regenerating it (it is a generated file)"
                    )
                else:
                    if missing:
                        ctx.warn(
                            f"{page.class_name} is hand-written and has no "
                            f"{', '.join(sorted(missing)[:4])}; those steps will need a human"
                        )
                    else:
                        ctx.note(f"{page.class_name} already exists - not regenerating it")
                    if page.class_name not in generation.reused_pages:
                        generation.reused_pages.append(page.class_name)
                    continue
            changes.append(
                FileChange(
                    path=str(PurePosixPath(layout["pages_dir"]) / f"{page.class_name}.ts"),
                    kind=ArtifactKind.PAGE_OBJECT,
                    content=render_page_object(page),
                    language="typescript",
                    rationale=(
                        f"Rendered from a planned spec: {len(page.locators)} verified locator(s), "
                        f"{len(page.methods)} method(s)."
                    ),
                    reuses=[page.base_class] if page.base_class else [],
                )
            )
        return changes

    # ------------------------------------------------------------------ #
    def _is_generated(self, ctx: AgentContext, path: str) -> bool:
        """Did this platform write the file? Only then may it rewrite it.

        The header is the marker, and it is written by the renderer on every
        page object it produces. Anything else is somebody's work.
        """
        read = self.tool(ctx, "fs.read_file", path=path)
        if not read.ok or not isinstance(read.data, str):
            return False
        first_line = read.data.splitlines()[0] if read.data else ""
        return any(marker in first_line for marker in _GENERATED_MARKERS)

    # -- 3b. step definitions -------------------------------------------- #
    def _render_steps(
        self, ctx: AgentContext, generation: GenerationPlan, plan: TestPlan, layout: dict[str, str]
    ) -> list[FileChange]:
        existing = {
            _normalise_step(s.name)
            for s in (ctx.repo_profile.symbols_of("step") if ctx.repo_profile else [])
        }
        new_steps = [s for s in generation.steps if _normalise_step(s.text) not in existing]
        reused = [s.text for s in generation.steps if _normalise_step(s.text) in existing]

        if not new_steps:
            ctx.note(f"all {len(reused)} step(s) already exist in the repository - no step file needed")
            return []

        page_names = [p.class_name for p in generation.pages] + list(plan.page_objects_reused)
        slug = re.sub(r"[^a-z0-9]+", "-", (plan.features[0].name if plan.features else "steps").lower()).strip("-")

        # A page the plan describes is not necessarily a page this run writes.
        # `_render_pages` skips any class that already exists in the repository,
        # and passing its PagePlan on to the step renderer told that renderer
        # "we are generating this, so trust its methods" -- which is how a plan
        # reused the real `LoginPage` and called `ensureTestUserExists()` and
        # `submitSignInWithValues()` on it. Neither exists. Only the classes
        # actually written this run get that trust; the rest are passed by name,
        # so their calls are checked against the index.
        written = {p.name for p in (ctx.repo_profile.symbols_of("page_object") if ctx.repo_profile else [])}
        pages_for_steps: list[Any] = [p for p in generation.pages if p.class_name not in written]
        pages_for_steps += [p.class_name for p in generation.pages if p.class_name in written]
        return [
            FileChange(
                path=str(PurePosixPath(layout["steps_dir"]) / f"{slug}.steps.ts"),
                kind=ArtifactKind.STEP_DEFINITION,
                content=render_steps(
                    new_steps,
                    # The plans, not just the names: a step must be bound to the
                    # method's real signature or it will not compile.
                    pages=pages_for_steps,
                    pages_import_path=_relative_import(layout["steps_dir"], layout["pages_dir"]),
                    existing_members=_existing_members(ctx),
                ),
                language="typescript",
                rationale=f"{len(new_steps)} new step(s) bound to Page Object methods; {len(reused)} reused.",
                reuses=sorted(set(reused))[:20] + [p for p in page_names if p],
            )
        ]

    # -- 4. test data ---------------------------------------------------- #
    # -- 5. API and database checks -------------------------------------- #
    def _api_changes(
        self, ctx: AgentContext, plan: TestPlan, layout: dict[str, str]
    ) -> list[FileChange]:
        """Render API checks, but only against endpoints the app revealed."""
        if not plan.api_checks:
            return []
        catalog = (
            ctx.application_map.api_catalog() if ctx.application_map is not None else []
        )
        if not catalog:
            ctx.note(
                "API checks were planned but no endpoint was observed during exploration; "
                "skipping rather than generating tests against guessed URLs"
            )
            return []

        checks = api_checks_from(plan.api_checks, catalog)
        dropped = len(plan.api_checks) - len(checks)
        if dropped > 0:
            ctx.warn(f"dropped {dropped} API check(s) naming an endpoint that was never observed")
        if not checks:
            return []

        feature = plan.features[0].name if plan.features else "API"
        ctx.note(f"generated {len(checks)} API check(s) against {len(catalog)} observed endpoint(s)")
        return [
            FileChange(
                path=str(PurePosixPath(layout["api_dir"]) / spec_file_name(feature, "api")),
                change_type=ChangeType.CREATE,
                kind=ArtifactKind.API_TEST,
                content=render_api_tests(checks, suite=feature),
                language="typescript",
                rationale=(
                    "Verifies the same criteria one layer below the UI, using endpoints "
                    "observed during exploration."
                ),
            )
        ]

    def _db_changes(
        self, ctx: AgentContext, plan: TestPlan, layout: dict[str, str]
    ) -> list[FileChange]:
        """Render database checks against a query helper the project supplies."""
        checks = db_checks_from(plan.db_checks)
        if not checks:
            return []
        feature = plan.features[0].name if plan.features else "Data"
        unparameterised = sum(1 for c in checks if not c.table)
        if unparameterised:
            ctx.note(
                f"{unparameterised} database check(s) named no table and are emitted as "
                "test.fixme rather than as assertions that would silently pass"
            )
        # `tests/utils/`, not `tests/support/`: the organisation standard says a
        # util belongs there, and the generator has to follow the rules it
        # enforces on everyone else.
        helper_path = str(PurePosixPath(layout["utils_dir"]) / "db.ts")
        helper_import = _relative_import(layout["api_dir"], layout["utils_dir"]) + "/db"
        changes = [
            FileChange(
                path=str(PurePosixPath(layout["api_dir"]) / spec_file_name(feature, "db")),
                change_type=ChangeType.CREATE,
                kind=ArtifactKind.DB_CHECK,
                content=render_db_checks(checks, suite=feature, db_helper_import=helper_import),
                language="typescript",
                rationale="Asserts persisted state directly, which the UI cannot prove.",
            )
        ]
        # Ship the stub the spec imports. Without it the missing module is a
        # compile error for the entire project, which hides every other result.
        if not self.tool(ctx, "fs.read_file", path=helper_path).ok:
            changes.append(
                FileChange(
                    path=helper_path,
                    change_type=ChangeType.CREATE,
                    kind=ArtifactKind.UTIL,
                    content=render_db_helper(),
                    language="typescript",
                    rationale="Throws until pointed at a test database, so a @database check cannot pass against nothing.",
                )
            )
        return changes

    # -- 6. visual regression -------------------------------------------- #
    def _visual_changes(
        self, ctx: AgentContext, plan: TestPlan, layout: dict[str, str]
    ) -> list[FileChange]:
        """Screenshot assertions for routes whose markup has settled.

        Opt-in, because a screenshot baseline is a commitment: somebody has to
        review and update it on every deliberate design change. Turning that on
        for a team that has not agreed to it produces a suite they delete.
        """
        settings = (ctx.standards.get("visual", {}) or {})
        if not settings.get("enabled", False):
            return []
        if ctx.application_map is None:
            return []

        candidates = ctx.application_map.visual_candidates(
            int(settings.get("required_stable_visits", 2) or 2)
        )
        if not candidates:
            ctx.note(
                "visual regression is enabled but no route has looked identical on "
                "consecutive explorations yet; nothing baselined"
            )
            return []

        checks = visual_checks_from(candidates, limit=int(settings.get("max_routes", 6) or 6))
        ratio = float(settings.get("max_diff_pixel_ratio", 0.01) or 0.01)
        for check in checks:
            check.max_diff_pixel_ratio = ratio

        feature = plan.features[0].name if plan.features else "Application"
        ctx.note(f"generated visual checks for {len(checks)} settled route(s)")
        return [
            FileChange(
                path=str(PurePosixPath(layout["visual_dir"]) / visual_spec_file_name(feature)),
                change_type=ChangeType.CREATE,
                kind=ArtifactKind.TEST_DATA,
                content=render_visual_tests(checks, suite=feature),
                language="typescript",
                rationale=(
                    "Catches layout and styling regressions that functional tests cannot see. "
                    "Only routes with stable markup are included."
                ),
            )
        ]

    def _data_changes(self, ctx: AgentContext, plan: TestPlan, layout: dict[str, str]) -> list[FileChange]:
        rows: dict[str, list[dict[str, str]]] = {}
        for feature in plan.features:
            for scenario in feature.scenarios:
                if scenario.examples:
                    rows[scenario.test_id or scenario.name] = scenario.examples
        if not rows:
            return []
        slug = re.sub(r"[^a-z0-9]+", "-", (plan.features[0].name if plan.features else "data").lower()).strip("-")
        return [
            FileChange(
                path=str(PurePosixPath(layout["data_dir"]) / f"{slug}.data.json"),
                kind=ArtifactKind.TEST_DATA,
                content=json.dumps(rows, indent=2) + "\n",
                language="json",
                rationale="Externalised Examples tables so datasets change without touching the feature file.",
            )
        ]


# =========================================================================== #
def _existing_members(ctx: AgentContext) -> dict[str, set[str]]:
    """Methods of the page objects already in the repository.

    The index records them, so a call onto a reused class can be checked rather
    than trusted. Without this a plan can reuse a real class and invent a method
    on it, which compiles in the model's head and nowhere else.
    """
    if ctx.repo_profile is None:
        return {}
    members: dict[str, set[str]] = {}
    for symbol in ctx.repo_profile.symbols_of("page_object"):
        if symbol.name:
            members[symbol.name] = set(symbol.members or [])
    return members


def _page_class_name(feature_name: str) -> str:
    name = pascal(feature_name)
    return name if name.endswith("Page") else name + "Page"


#: A Page Object name a reviewer would accept: PascalCase, not absurdly long,
#: and not obviously an echo of the prompt.
_PROMPT_ECHO = ("target", "object", "catalogue", "scenario", "existing", "verified")


def _plausible_class_name(name: str) -> bool:
    if not name or len(name) > 48 or not re.match(r"^[A-Z][A-Za-z0-9]*$", name):
        return False
    lowered = name.lower()
    return not any(token in lowered for token in _PROMPT_ECHO)


def _guess_route(ctx: AgentContext) -> str:
    if ctx.exploration and ctx.exploration.snapshots:
        for snapshot in ctx.exploration.snapshots:
            route = snapshot.route_pattern or ""
            if route and route != "/":
                return route
    title = (ctx.requirement.title if ctx.requirement else "").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", title).strip("-")
    return f"/{slug}" if slug else "/"


def _normalise_step(text: str) -> str:
    """Compare step intent, ignoring keyword, parameters and punctuation."""
    stripped = re.sub(r"^(Given|When|Then|And|But|\*)\s+", "", str(text).strip(), flags=re.IGNORECASE)
    stripped = re.sub(r"\{[a-z]+\}", "", stripped)
    stripped = re.sub(r"['\"][^'\"]*['\"]", "", stripped)
    stripped = re.sub(r"<[^>]+>", "", stripped)
    return re.sub(r"[^a-z0-9]+", " ", stripped.lower()).strip()


def _relative_import(from_dir: str, to_dir: str) -> str:
    """POSIX relative import specifier between two repository directories."""
    from_parts = [p for p in from_dir.strip("/").split("/") if p]
    to_parts = [p for p in to_dir.strip("/").split("/") if p]
    common = 0
    for a, b in zip(from_parts, to_parts, strict=False):
        if a != b:
            break
        common += 1
    ups = [".."] * (len(from_parts) - common)
    downs = to_parts[common:]
    joined = "/".join(ups + downs)
    return joined if joined.startswith(".") else (f"./{joined}" if joined else ".")
