"""Visual regression specs.

Screenshots are already captured during exploration, so the marginal cost of
visual coverage is close to zero — and it catches the whole class of defect
that functional tests are blind to: the button that still works but is now
invisible, the layout that collapses at 375px, the stylesheet that failed to
load.

Two decisions make this useful rather than annoying:

* **Playwright does the pixel comparison, not this platform.** `toHaveScreenshot()`
  already handles baselines, per-platform snapshots, anti-aliasing tolerance and
  the update workflow (`--update-snapshots`). Reimplementing that in Python
  would be worse in every respect, so the generated spec delegates to it.
* **Only settled pages get a spec.** A visual test on a page with a live clock
  fails every run until somebody deletes it, and a suite that cries wolf stops
  being read. A route qualifies only once its markup has come back identical on
  consecutive explorations, and dynamic regions are masked rather than tolerated.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

#: Elements whose content changes on every load. Compared against them, a
#: pixel-perfect assertion is guaranteed to fail, so they are masked out rather
#: than being allowed to lower the threshold for the whole page.
DEFAULT_MASK_PATTERNS = (
    "[data-testid*='timestamp']",
    "[data-testid*='clock']",
    "time",
    ".relative-time",
)

#: Widths worth checking. Most layout regressions show up at the boundaries.
DEFAULT_VIEWPORTS = ((1280, 720, "desktop"), (375, 812, "mobile"))


@dataclass
class VisualCheck:
    route: str
    name: str = ""
    viewports: tuple[tuple[int, int, str], ...] = DEFAULT_VIEWPORTS
    masks: list[str] = field(default_factory=lambda: list(DEFAULT_MASK_PATTERNS))
    max_diff_pixel_ratio: float = 0.01
    full_page: bool = True

    @property
    def label(self) -> str:
        return self.name or self.route


def visual_checks_from(
    candidates: list[dict[str, Any]],
    *,
    limit: int = 8,
    masks: list[str] | None = None,
) -> list[VisualCheck]:
    """Turn the map's stable routes into checks, worst-churn excluded already."""
    checks: list[VisualCheck] = []
    for entry in candidates[:limit]:
        route = str(entry.get("route") or "").strip()
        if not route:
            continue
        checks.append(
            VisualCheck(
                route=route,
                name=str(entry.get("title") or "").strip()[:80],
                masks=list(masks) if masks is not None else list(DEFAULT_MASK_PATTERNS),
            )
        )
    return checks


def render_visual_tests(checks: list[VisualCheck], *, suite: str) -> str:
    """A Playwright spec that delegates pixel comparison to Playwright."""
    lines: list[str] = [
        f"// {suite} - visual regression generated by QAgentic.",
        "//",
        "// Baselines are Playwright's, not ours. The first run writes them; after that",
        "// a diff fails the test. To accept an intentional design change, re-run with",
        "//   npx playwright test --update-snapshots",
        "//",
        "// Only routes whose markup was identical on consecutive explorations are here:",
        "// a visual test on a page that changes every load is a false alarm generator.",
        "import { expect, test } from '@playwright/test';",
        "",
        f"test.describe('{_escape(suite)} @visual', () => {{",
    ]

    for check in checks:
        for width, height, label in check.viewports:
            snapshot = f"{_slug(check.route)}-{label}.png"
            lines.append(
                f"  test('{_escape(check.label)} looks right at {label} ({width}px)', "
                f"async ({{ page }}) => {{"
            )
            lines.append(f"    await page.setViewportSize({{ width: {width}, height: {height} }});")
            lines.append(f"    await page.goto('{_escape(check.route)}');")
            # Wait for the network to settle, or the first run bakes a
            # half-loaded page into the baseline and every later run "regresses".
            lines.append("    await page.waitForLoadState('networkidle');")
            lines.append("")
            lines.append(f"    await expect(page).toHaveScreenshot('{snapshot}', {{")
            lines.append(f"      fullPage: {str(check.full_page).lower()},")
            lines.append(f"      maxDiffPixelRatio: {check.max_diff_pixel_ratio},")
            if check.masks:
                masks = ",\n".join(f"        page.locator(\"{m}\")" for m in check.masks)
                lines.append("      mask: [")
                lines.append(masks + ",")
                lines.append("      ],")
            lines.append("    });")
            lines.append("  });")
            lines.append("")

    while lines and lines[-1] == "":
        lines.pop()
    lines.append("});")
    lines.append("")
    return "\n".join(lines)


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-") or "root"


def _escape(text: str) -> str:
    return str(text).replace("\\", "\\\\").replace("'", "\\'")


def spec_file_name(feature_name: str) -> str:
    return f"{_slug(feature_name)}.visual.spec.ts"


__all__ = [
    "DEFAULT_MASK_PATTERNS",
    "DEFAULT_VIEWPORTS",
    "VisualCheck",
    "render_visual_tests",
    "spec_file_name",
    "visual_checks_from",
]
