"""The stage that closes generated gaps, or refuses to pretend they are closed.

Before this stage existed, a run could write a feature, a page object and a
step file, compile all three, and report success with three of its steps doing
literally nothing. Everything the pipeline checked was satisfied; nothing was
verified.

The agent works on the bundle in memory, before any file reaches disk, so a gap
is closed or named before a human is asked to approve a diff.
"""

from __future__ import annotations

import asyncio

import pytest

from agents.base import AgentContext
from agents.step_coverage.agent import StepCoverageAgent
from packages.aiqa_types.enums import ArtifactKind, RunMode
from packages.aiqa_types.models import CodeBundle, FileChange, Project

PAGE = """// ResidentsPage - generated by QAgentic.
import { BasePage } from './BasePage';

export class ResidentsPage extends BasePage {
  readonly path = '/residents/new';

  async fillForm(fullName: string): Promise<void> {
    await this.fullName.fill(fullName);
  }
}
"""

CATALOG = [
    {"page": "/residents/new", "name": "Email", "role": "textbox",
     "locator": "getByTestId('resident-email')", "confidence": 0.98},
    {"page": "/residents/new", "name": "Create resident", "role": "button",
     "locator": "getByTestId('resident-submit')", "confidence": 0.98},
    {"page": "/residents/new", "name": "Confirmation message", "role": "status",
     "locator": "getByTestId('resident-confirmation')", "confidence": 0.95},
]


def _run(steps_source: str, page_source: str = PAGE, catalog: list | None = None) -> tuple[AgentContext, CodeBundle]:
    bundle = CodeBundle(
        run_id="r", plan_id="p",
        changes=[
            FileChange(path="tests/pages/ResidentsPage.ts", kind=ArtifactKind.PAGE_OBJECT, content=page_source),
            FileChange(path="tests/steps/residents.steps.ts", kind=ArtifactKind.STEP_DEFINITION, content=steps_source),
        ],
    )
    ctx = AgentContext(
        run_id="r",
        project=Project(org_id="o", name="p", repository_path="."),
        instruction="x",
        mode=RunMode.FULL,
    )
    ctx.code_bundle = bundle
    ctx.metadata["locator_catalog"] = CATALOG if catalog is None else catalog
    asyncio.run(StepCoverageAgent().run(ctx))
    return ctx, bundle


def _steps(*bodies: str) -> str:
    head = (
        "// Generated by QAgentic - step definitions.\n"
        "import { Given, When, Then } from '@cucumber/cucumber';\n"
        "import { ResidentsPage } from '../pages/ResidentsPage';\n\n"
        "let residentsPage!: ResidentsPage;\n\n"
    )
    return head + "\n".join(bodies)


PENDING_WITH_VALUE = """When('I enter the resident email address {string}', async function (value1: string) {
  residentsPage ??= new ResidentsPage(this.page);
  // TODO(aiqa): ResidentsPage has no fillEmail().
  return 'pending';
});
"""

INVENTED_METHOD = """When('I click the Create resident button', async function () {
  residentsPage ??= new ResidentsPage(this.page);
  await residentsPage.submitTheForm();
});
"""

UNRESOLVABLE = """Then('the accountant reconciles the quarterly ledger', async function () {
  // TODO(aiqa): bind this step to a Page Object method.
  return 'pending';
});
"""

PENDING_WITHOUT_VALUE = """When('I enter the resident email address', async function () {
  residentsPage ??= new ResidentsPage(this.page);
  return 'pending';
});
"""

BOUND = """When('I complete the form {string}', async function (value1: string) {
  residentsPage ??= new ResidentsPage(this.page);
  await residentsPage.fillForm(value1);
});
"""


# --------------------------------------------------------------------------- #
# Closing gaps
# --------------------------------------------------------------------------- #
def test_a_pending_step_is_bound_to_an_observed_element() -> None:
    ctx, bundle = _run(_steps(PENDING_WITH_VALUE))
    steps = bundle.changes[1].content
    page = bundle.changes[0].content

    assert "return 'pending';" not in steps, "the gap is closed, not annotated"
    assert "await residentsPage.fillResidentEmailAddress(value1);" in steps
    assert "getByTestId('resident-email')" in page, "the locator comes from the crawl"
    assert not ctx.metadata.get("automation_blocked")


def test_a_method_the_page_never_declared_is_generated() -> None:
    """`submitTheForm()` compiles in the model's head and nowhere else."""
    _, bundle = _run(_steps(INVENTED_METHOD))
    steps, page = bundle.changes[1].content, bundle.changes[0].content

    assert "submitTheForm" not in steps
    assert "await residentsPage.clickCreateResident();" in steps
    assert "async clickCreateResident()" in page


def test_an_assertion_brings_its_own_import() -> None:
    """The original render had no reason to import `expect`."""
    source = """Then('I should see the confirmation message {string}', async function (value1: string) {
  residentsPage ??= new ResidentsPage(this.page);
  return 'pending';
});
"""
    _, bundle = _run(_steps(source))
    page = bundle.changes[0].content
    assert "await expect(" in page
    assert "import { expect } from '@playwright/test';" in page


def test_an_already_bound_step_is_left_exactly_alone() -> None:
    _, bundle = _run(_steps(BOUND))
    assert "await residentsPage.fillForm(value1);" in bundle.changes[1].content
    assert bundle.changes[0].content == PAGE, "nothing needed adding"


# --------------------------------------------------------------------------- #
# Refusing to pretend
# --------------------------------------------------------------------------- #
def test_a_step_with_no_matching_element_blocks_the_run() -> None:
    ctx, bundle = _run(_steps(UNRESOLVABLE))

    blocked = ctx.metadata.get("automation_blocked")
    assert blocked, "an unimplemented step must stop this being called complete"
    assert blocked[0]["step"] == "the accountant reconciles the quarterly ledger"
    assert blocked[0]["reason"], "a block without a reason gives a human nothing to do"
    assert any("AUTOMATION_BLOCKED" in w for w in ctx.warnings)
    assert "return 'pending';" in bundle.changes[1].content, (
        "and the step stays honestly pending rather than being faked"
    )


def test_a_step_that_supplies_no_value_says_so_precisely() -> None:
    """The reason has to be specific enough to act on.

    "Blocked" alone sends someone to read a diff. "Quote a value in the step"
    is a change they can make in five seconds.
    """
    ctx, _ = _run(_steps(PENDING_WITHOUT_VALUE))
    blocked = ctx.metadata.get("automation_blocked")
    assert blocked
    assert "supplies none" in blocked[0]["reason"]


def test_a_call_is_never_emitted_with_an_undeclared_argument() -> None:
    """`fillEmail(value)` in a callback that declares no `value` does not compile.

    The main renderer refuses this by emitting no binding at all; this stage has
    to refuse it for the same reason, or it reintroduces the defect one layer
    further on.
    """
    _, bundle = _run(_steps(PENDING_WITHOUT_VALUE))
    steps = bundle.changes[1].content
    assert "fillResidentEmailAddress(value)" not in steps
    assert "return 'pending';" in steps


def test_an_empty_catalogue_blocks_everything_rather_than_guessing() -> None:
    """No crawl, no evidence, no invention."""
    ctx, bundle = _run(_steps(PENDING_WITH_VALUE), catalog=[])
    assert ctx.metadata.get("automation_blocked")
    assert "return 'pending';" in bundle.changes[1].content


# --------------------------------------------------------------------------- #
# Bounds and bookkeeping
# --------------------------------------------------------------------------- #
def test_several_gaps_in_one_file_are_all_handled() -> None:
    ctx, bundle = _run(_steps(PENDING_WITH_VALUE, INVENTED_METHOD, UNRESOLVABLE))
    coverage = ctx.metadata["step_coverage"]

    assert len(coverage["closed"]) == 2
    assert len(coverage["blocked"]) == 1
    assert bundle.changes[1].content.count("return 'pending';") == 1


def test_the_loop_stops_as_soon_as_nothing_moves() -> None:
    """Every pass sees the same evidence, so a pass that closes nothing is the last.

    Without this the stage would spend three passes reaching the same answer,
    and on free models the report line alone is not worth the wait.
    """
    ctx, _ = _run(_steps(UNRESOLVABLE))
    assert not any("3 pass" in note for note in ctx.notes)


def test_bytes_are_updated_when_content_changes() -> None:
    """The bundle reports its own size; a stale count misleads the approval view."""
    _, bundle = _run(_steps(PENDING_WITH_VALUE))
    for change in bundle.changes:
        assert change.bytes == len(change.content.encode("utf-8"))


@pytest.mark.parametrize("mode", [RunMode.EXECUTE_ONLY, RunMode.HEAL_ONLY])
def test_modes_that_generate_nothing_are_skipped(mode: RunMode) -> None:
    ctx = AgentContext(
        run_id="r", project=Project(org_id="o", name="p", repository_path="."),
        instruction="x", mode=mode,
    )
    assert StepCoverageAgent().skip_reason(ctx)


def test_the_stage_runs_between_generation_and_standards() -> None:
    """A step that does nothing is not a style problem; standards cannot see it."""
    from agents.orchestrator.graph import build_default_nodes

    nodes = build_default_nodes()
    assert "step_coverage" in nodes, "the stage is not in the graph at all"

    # Follow the edges rather than trusting declaration order.
    assert nodes["code_generation"].route(None) == "step_coverage"
    assert nodes["step_coverage"].route(None) == "standards"


# --------------------------------------------------------------------------- #
# The completion gate
# --------------------------------------------------------------------------- #
def test_a_blocked_step_leads_the_report() -> None:
    """A step nothing implements is not a smaller success.

    The headline used to lead with files written, so a run with three unbound
    steps read as finished work — the exact impression this stage exists to
    prevent.
    """
    from agents.reporting.agent import _headline

    facts = {
        "execution_blocked": "", "total": 6, "passed": 6, "failed": 0,
        "pass_rate": 100.0, "scenarios": 6, "files_changed": 4,
        "heals_verified": 0, "heals_proposed": 0, "product_defects": [],
        "blocked_steps": [
            {"step": "the accountant reconciles the ledger", "reason": "no verified element matches it"},
            {"step": "something else", "reason": "another reason"},
        ],
    }
    headline = _headline(facts)

    assert headline.startswith("AUTOMATION_BLOCKED")
    assert "the accountant reconciles the ledger" in headline, "name the step, not just the count"
    assert "no verified element matches it" in headline, "and say why"
    assert "and 1 more" in headline


def test_a_clean_run_still_reports_normally() -> None:
    """The gate must not make a genuinely finished run look blocked."""
    from agents.reporting.agent import _headline

    facts = {
        "execution_blocked": "", "total": 6, "passed": 6, "failed": 0,
        "pass_rate": 100.0, "scenarios": 6, "files_changed": 4,
        "heals_verified": 0, "heals_proposed": 0, "product_defects": [],
        "blocked_steps": [],
    }
    assert _headline(facts) == "6/6 tests passing (100.0%)"


# --------------------------------------------------------------------------- #
# A gap closed against the wrong page
# --------------------------------------------------------------------------- #
# Found in a real autopilot run against the demo application. The step
# "I submit the form with all fields completed", belonging to the *residents*
# form, was bound to `LoginPage.submit()` — the best-scoring `submit` anywhere
# in the repository — and recorded as a closed gap. The generated file then read
#
#     loginPage ??= new LoginPage(this.page);
#     await loginPage.submit();
#
# in a file that imports neither, which failed to compile and took the whole
# suite with it. Two defects, and the compile error is the lesser one: had the
# import been right, the suite would have gone green having signed in instead of
# submitting the form under test.
SUBMIT_GAP = """When('I submit the form with all fields completed', async function () {
  residentsPage ??= new ResidentsPage(this.page);
  await residentsPage.submitEverything();
});
"""


class _Symbol:
    def __init__(self, name: str, members: set[str]) -> None:
        self.name = name
        self.members = sorted(members)


class _Profile:
    """A repository holding two pages, only one of which is under test."""

    def __init__(self, pages: dict[str, set[str]]) -> None:
        self._pages = pages

    def symbols_of(self, kind: str) -> list[_Symbol]:
        if kind != "page_object":
            return []
        return [_Symbol(name, members) for name, members in self._pages.items()]


def _run_with_repo(steps_source: str, pages: dict[str, set[str]]):
    bundle = CodeBundle(
        run_id="r", plan_id="p",
        changes=[
            FileChange(path="tests/pages/ResidentsPage.ts", kind=ArtifactKind.PAGE_OBJECT, content=PAGE),
            FileChange(path="tests/steps/residents.steps.ts", kind=ArtifactKind.STEP_DEFINITION, content=steps_source),
        ],
    )
    ctx = AgentContext(
        run_id="r",
        project=Project(org_id="o", name="p", repository_path="."),
        instruction="x",
        mode=RunMode.FULL,
    )
    ctx.code_bundle = bundle
    ctx.metadata["locator_catalog"] = []
    ctx.repo_profile = _Profile(pages)
    asyncio.run(StepCoverageAgent().run(ctx))
    return ctx, bundle


def _steps_file(bundle: CodeBundle) -> str:
    return next(c.content for c in bundle.changes if c.kind == ArtifactKind.STEP_DEFINITION)


def test_a_step_is_never_bound_to_a_method_on_another_page() -> None:
    """`submit` on the login page is not this form's `submit`.

    However well the words score. A binding to the wrong page is worse than an
    open gap: it compiles, it runs, and it verifies a different screen.
    """
    ctx, bundle = _run_with_repo(
        _steps(SUBMIT_GAP),
        {"LoginPage": {"submit", "signIn"}, "ResidentsPage": {"goto"}},
    )
    source = _steps_file(bundle)

    assert "LoginPage" not in source
    assert "loginPage" not in source
    # Honestly unresolved rather than dishonestly closed.
    assert ctx.metadata.get("automation_blocked")


def test_the_same_page_is_still_reused() -> None:
    """The rung must keep working for the case it exists for."""
    _, bundle = _run_with_repo(
        _steps(SUBMIT_GAP),
        {"LoginPage": {"submit"}, "ResidentsPage": {"submitTheCompletedForm", "goto"}},
    )
    source = _steps_file(bundle)

    assert "residentsPage.submitTheCompletedForm()" in source
    assert "LoginPage" not in source


def test_a_page_the_file_cannot_name_is_never_written_into_it() -> None:
    """The backstop, in case a resolution ever crosses pages again.

    `Cannot find name 'LoginPage'` does not fail one scenario, it fails the
    compile, and a suite that does not compile runs nothing at all.
    """
    changes = [
        FileChange(path="tests/pages/ResidentsPage.ts", kind=ArtifactKind.PAGE_OBJECT, content=PAGE),
        FileChange(path="tests/steps/residents.steps.ts", kind=ArtifactKind.STEP_DEFINITION,
                   content=_steps(SUBMIT_GAP)),
    ]
    assert StepCoverageAgent._can_reference(changes, "ResidentsPage")
    assert not StepCoverageAgent._can_reference(changes, "LoginPage")

