"""Reuse means "it already does the job", not "never touch it".

An early run — before exploration worked — left a `ResidentRegistrationPage`
with no locators at all and a single `expectSuccess` method. Every later run
dutifully reused it, because the rule was simply "a class that exists is not
regenerated", and produced eight step definitions bound to methods it does not
have. One bad file, generated once, was poisoning the repository indefinitely.

The line that matters is authorship. A file this platform wrote says so on its
first line and may be rewritten. A hand-written Page Object is somebody's work:
it is left alone, and its missing methods surface as TODOs for a human.
"""

from __future__ import annotations

from typing import Any

import pytest

from agents.code_generation.agent import CodeGenerationAgent
from agents.code_generation.renderer import GenerationPlan, MethodPlan, PagePlan

GENERATED_HEADER = "// ResidentRegistrationPage - generated by AI QA Engineer.\nexport class X {}"
HANDWRITTEN = "// Our own page object, do not touch.\nexport class X {}"


class _Result:
    def __init__(self, ok: bool, data: Any = None) -> None:
        self.ok = ok
        self.data = data
        self.error = ""


class _Ctx:
    """Only what `_render_pages` reads."""

    def __init__(self, files: dict[str, str], members: dict[str, set[str]]) -> None:
        self.files = files
        self.members = members
        self.notes: list[str] = []
        self.warnings: list[str] = []
        self.repo_profile = _Profile(members)

    def note(self, text: str) -> None:
        self.notes.append(text)

    def warn(self, text: str) -> None:
        self.warnings.append(text)


class _Symbol:
    def __init__(self, name: str, members: set[str]) -> None:
        self.name = name
        self.members = sorted(members)


class _Profile:
    def __init__(self, members: dict[str, set[str]]) -> None:
        self._members = members

    def symbols_of(self, kind: str) -> list[_Symbol]:
        assert kind == "page_object"
        return [_Symbol(name, members) for name, members in self._members.items()]


@pytest.fixture
def agent(monkeypatch: pytest.MonkeyPatch) -> CodeGenerationAgent:
    instance = CodeGenerationAgent()

    def fake_tool(self: Any, ctx: _Ctx, name: str, **kwargs: Any) -> _Result:
        if name == "fs.read_file":
            content = ctx.files.get(kwargs["path"])
            return _Result(content is not None, content)
        raise AssertionError(f"unexpected tool {name}")

    monkeypatch.setattr(CodeGenerationAgent, "tool", fake_tool)
    return instance


LAYOUT = {"pages_dir": "tests/pages"}


def _plan() -> GenerationPlan:
    return GenerationPlan(
        pages=[
            PagePlan(
                class_name="ResidentRegistrationPage",
                route="/residents/new",
                base_class="BasePage",
                locators={"fullName": "getByTestId('resident-name')"},
                methods=[
                    MethodPlan(name="fillResidentDetails", kind="action", locators=["fullName"]),
                    MethodPlan(name="expectSuccess", kind="assertion", params=["message"]),
                ],
            )
        ]
    )


def test_an_incomplete_generated_page_is_rewritten(agent: CodeGenerationAgent) -> None:
    ctx = _Ctx(
        {"tests/pages/ResidentRegistrationPage.ts": GENERATED_HEADER},
        {"ResidentRegistrationPage": {"expectSuccess"}},
    )
    changes = agent._render_pages(ctx, _plan(), LAYOUT)

    assert [c.path for c in changes] == ["tests/pages/ResidentRegistrationPage.ts"]
    assert "fillResidentDetails" in changes[0].content
    assert any("regenerating" in note for note in ctx.notes), ctx.notes


def test_a_complete_page_is_left_alone(agent: CodeGenerationAgent) -> None:
    ctx = _Ctx(
        {"tests/pages/ResidentRegistrationPage.ts": GENERATED_HEADER},
        {"ResidentRegistrationPage": {"expectSuccess", "fillResidentDetails"}},
    )
    plan = _plan()
    assert agent._render_pages(ctx, plan, LAYOUT) == []
    assert plan.reused_pages == ["ResidentRegistrationPage"]


def test_a_hand_written_page_is_never_overwritten(agent: CodeGenerationAgent) -> None:
    """Even when it is missing exactly what the plan needs."""
    ctx = _Ctx(
        {"tests/pages/ResidentRegistrationPage.ts": HANDWRITTEN},
        {"ResidentRegistrationPage": {"expectSuccess"}},
    )
    plan = _plan()
    assert agent._render_pages(ctx, plan, LAYOUT) == []
    assert plan.reused_pages == ["ResidentRegistrationPage"]
    assert any("hand-written" in warning for warning in ctx.warnings), ctx.warnings


def test_a_page_that_does_not_exist_is_simply_generated(agent: CodeGenerationAgent) -> None:
    ctx = _Ctx({}, {})
    changes = agent._render_pages(ctx, _plan(), LAYOUT)
    assert [c.path for c in changes] == ["tests/pages/ResidentRegistrationPage.ts"]
